# Generated by Django 3.0.8 on 2020-08-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lastEdit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
