# Generated by Django 3.0.8 on 2020-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200805_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch', to='auctions.Listing'),
        ),
    ]
