# Generated by Django 3.0.8 on 2020-08-05 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200805_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 5, 14, 13, 46, 470876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 5, 14, 13, 46, 470876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 5, 14, 13, 46, 470876, tzinfo=utc)),
        ),
    ]
