# Generated by Django 3.0.8 on 2020-08-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200805_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auctions.Listing'),
        ),
    ]
