# Generated by Django 3.0.8 on 2020-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200806_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
