# Generated by Django 3.0.8 on 2020-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_wonlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonlisting',
            name='didWarning',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
